 // Source code is unavailable, and was generated by the Fernflower decompiler.
import java.util.Scanner;

public class day1ReverseNumber {
   public static void main(String[] var0) {
      Scanner var1 = new Scanner(System.in);
      int var2 = var1.nextInt();

      int var3;
      for(var3 = 0; var2 > 0; var2 /= 10) {
         int var4 = var2 % 10;
         var3 = var3 * 10 + var4;
      }

      System.out.println("Reverse = " + var3);
   }
}
